# Generated by Django 5.2.6 on 2025-09-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitnow', '0004_alter_complaint_assigned_worker_alter_complaint_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='title',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
