# Generated by Django 5.2.6 on 2025-09-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitnow', '0005_remove_workerprofile_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(choices=[('BTech', 'B.Tech'), ('MTech', 'M.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('PhD', 'PhD')], max_length=10)),
                ('admission_number', models.CharField(max_length=50)),
                ('year_of_admission', models.IntegerField()),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
