# Generated by Django 5.2.6 on 2025-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitnow', '0006_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_admission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
