# Generated by Django 5.2.6 on 2025-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitnow', '0007_alter_studentprofile_year_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='specialization',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
